### ISSUE TITLE
Issues with Python 3.6

### ISSUE THREAD

**Issue by suminb** [sivel/flask-lambda#1]
As AWS Lambda announced their [support for Python 3.6](https://aws.amazon.com/about-aws/whats-new/2017/04/aws-lambda-supports-python-3-6/) a few days ago, I was testing `flask-lambda` with Python 3.6.

Under the `FlaskLambda.__call__` method, there is this:

        body = next(self.wsgi_app(
            make_environ(event),
            response.start_response
        ))

However, the type of `body` always becomes `bytes`, and you ways end up getting the following error message when calling it via AWS Lambda.

    An error occurred during JSON serialization of response: b'(your response)' is not JSON serializable

I know the following patch (`body` -> `body.decode('utf-8')`) will get my work done for now, but it is probably not a good general solution.

        return {
            'statusCode': response.status,
            'headers': response.response_headers,
            'body': body.decode('utf-8')
        }

What would be a good resolution for this issue?

**Comment by sivel** [comment]
I believe that is an error in your application and not flask_lambda.  flask_lambda doesn't concern itself with your encoding.  If you return a bytestring from your view function, flask_lambda will just proxy it through.

It is your responsibility to make sure you are returning a `str` type in python3.

**Comment by huyphan** [comment]
@sivel: I'm late to the game, but I'm afraid this is something flask_lambda should be concerned about. Even if the view function returns an object of `str` type, Flask still encodes it to `bytes`. It's pretty easy to to confirm that with the following snippet: 
```
from flask import Flask

def start_response(self, *args, **kargs):
    return

class FlaskFooBar(Flask):
    def __call__(self, event, context):
        body = next(self.wsgi_app(event, start_response))

        print(type(body))

        return super(FlaskFooBar, self).__call__(event, context)


app = FlaskFooBar(__name__)
@app.route('/')
def hello_world():
    return 'Hello, World'
```

Your console would print out `<class 'str'>` in Python2 and `<class 'bytes'>` in Python3. Would you be interested in an PR for this (and some other minor optimization for multiple Python versions compatibility)?
