### ISSUE TITLE
Print out the event to the logs in flask_lambda.py

### ISSUE THREAD

**Issue by lorienpatt** [sivel/flask-lambda#12]
In flask_lambda.py you have a line of code that prints out the whole event being passed to the lambda.  This is a huge security issue because you have now printed out everything about the request (including headers containing cookies, authoriation tokens, etc). 
https://github.com/techjacker/flask-lambda/blob/59b6e6fcd7a3edc61a4557b06718a67191958917/flask_lambda.py#L42

**Comment by sivel** [comment]
That is not my repo. This repo doesn't include that print statement.

https://github.com/sivel/flask-lambda/blob/master/flask_lambda.py#L40
