### ISSUE TITLE
Is that project still alive?

### ISSUE THREAD

**Issue by dchaplinsky** [sivel/flask-lambda#2]
I've tried to use it, found some issues, fixed them.

Are you interested in PR?

**Comment by shovonnn** [comment]
i am going to use it for a project. can you let me know what are the issues?

**Comment by dchaplinsky** [comment]
Problems when making test calls through API Gateway.

Check my version:
https://gist.github.com/dchaplinsky/22e209cef2a57c2620dd8da487b84515

**Comment by shovonnn** [comment]
yeah i did encounter that.
thanks for the fix.
@sivel can you merge this change?

**Comment by mrunion** [comment]
Yes, same issue when testing with API Gateway. I wonder if this project is still alive as well.

**Comment by sivel** [comment]
This project is still alive.  Also when testing API gateway, you need to ensure that you have edited the body of the test correctly.  I properly edited body is included in the readme.

Also I see no fix, I see a gist with code, but no indication of what changes were made.  Submit PRs for fixes.

**Comment by dchaplinsky** [comment]
https://gist.github.com/dchaplinsky/31d0166f9db45c3a82f62b838aa23ba8

**Comment by dchaplinsky** [comment]
Will do the PR a proper bit later today.
